// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.0
// - protoc             (unknown)
// source: api/edn/v1/edn.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEdnReceiver = "/api.edn.v1.Edn/Receiver"

type EdnHTTPServer interface {
	Receiver(context.Context, *ReceiverRequest) (*ReceiverReply, error)
}

func RegisterEdnHTTPServer(s *http.Server, srv EdnHTTPServer) {
	r := s.Route("/")
	r.POST("/key/receive", _Edn_Receiver0_HTTP_Handler(srv))
}

func _Edn_Receiver0_HTTP_Handler(srv EdnHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReceiverRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEdnReceiver)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Receiver(ctx, req.(*ReceiverRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReceiverReply)
		return ctx.Result(200, reply)
	}
}

type EdnHTTPClient interface {
	Receiver(ctx context.Context, req *ReceiverRequest, opts ...http.CallOption) (rsp *ReceiverReply, err error)
}

type EdnHTTPClientImpl struct {
	cc *http.Client
}

func NewEdnHTTPClient(client *http.Client) EdnHTTPClient {
	return &EdnHTTPClientImpl{client}
}

func (c *EdnHTTPClientImpl) Receiver(ctx context.Context, in *ReceiverRequest, opts ...http.CallOption) (*ReceiverReply, error) {
	var out ReceiverReply
	pattern := "/key/receive"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEdnReceiver))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
