// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SK-builder/internal/biz"
	"SK-builder/internal/conf"
	"SK-builder/internal/data"
	"SK-builder/internal/infrastructure/otel/trace"
	"SK-builder/internal/server"
	"SK-builder/internal/service"
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	receiverRepo := data.NewReceiverRepo(dataData, logger)
	receiverUsecase := biz.NewReceiverUsecase(receiverRepo, logger)
	receiverService := service.NewReceiverService(receiverUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, receiverService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, receiverService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

func wireProvider(contextContext context.Context, confServer *conf.Server, logger log.Logger) (func(), error) {
	client := trace.NewTracerClient(confServer)
	exporter := trace.NewTracerExporter(contextContext, client)
	v, err := NewProvider(contextContext, confServer, exporter)
	if err != nil {
		return nil, err
	}
	return v, nil
}
